config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  root :to => "home#index"
  get 'project_overview', to: 'home#project_overview'
  get 'project_download', to: 'home#project_download'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #Using default credentials now, can extend to having any user store their
  #own encrypted organization and api_key.
  def user_api
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
  include ApplicationHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'gc_fetch/gc_fetch'

  def index
    @@api = GatherContentApi.new(ENV["ORGANIZATION"], ENV["API_KEY"], 'x')
    mash = Hashie::Mash.new(@@api.get_projects)
    mash.shift #Can append .shift to api call in console, won't run on server.
    clean_mash = mash.projects.each {|clean| clean_ampersands(clean.name)}
    @user_projects = clean_mash.sort_by {|project| project.name}
  end

  def project_overview
    @project_id_number = params[:id]
    @project_name = params[:name]
    mash = Hashie::Mash.new(@@api.get_pages_by_project(@project_id_number))
    mash.shift
    @page_array = mash.first.drop(1).flatten!
    @nested_page_array = create_hash(@page_array)
  end

  def project_download
    @project_id_number = params[:id]
    @project_name = params[:name]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def clean_ampersands(name)
    name.gsub! /\b&amp;\b/, "&"
  end

  def create_hash(m)
    by_id = m.group_by(&:id)
    page_hash = m.group_by { |page| by_id[page.parent_id]}
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
.container
  .jumbotron.text-center
    .row
      %h2
        GC Client
    .row
      %p
        GatherContent is annoying. Why not build a resource to list all projects and pull down what you need?
  .jumbotron
    .row
      .panel.panel-default
        .panel-heading
          %h3
            G5 Projects in GatherContent
        .panel-body
          - @user_projects.each do |project|
            .col-md-6
              .panel
                %p
                  = project.name
            .col-md-4-offset-6
              .panel
                %p
                  = link_to 'Show details', project_overview_path(:id => project.id, :name => project.name)

      

app/views/home/project_overview.html.haml
.container
  .jumbotron
    .row
      .panel.panel-default
        .panel-heading
          %h3
            Break it down for
            = @project_name
            (
            = @project_id_number
            )
        .panel-body
          - @page_array.each do |page|
            - if page.parent_id == "0"
              .panel
                %h3
                  = page.name
            - else
              %p
                = page.name         
    

app/views/layouts/_footer.html.haml
.footer
  .container
    .row
      .col-md-4
        %p
          ©UnitedWebFarmers

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    %ul.nav.navbar-nav.navbar-right
      %li
        = link_to 'Log Off', destroy_user_session_path, method: 'delete'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'GC Client'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'GC Client'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = favicon_link_tag "favicon(1).ico"
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield
    %footer
      = render 'layouts/footer'